spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    # hibernate:
    #   ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes (900 seconds)
    refreshTokenExpiration: 604800 # 7 days
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000
